# Generated by Django 4.0.6 on 2022-09-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('about_alumni', models.TextField()),
                ('mob1', models.IntegerField()),
                ('mob2', models.IntegerField()),
                ('email', models.TextField()),
                ('passout', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=25)),
                ('prn_no', models.CharField(max_length=25)),
                ('job_status', models.CharField(max_length=20)),
                ('org_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='eventgallary',
            name='event_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics_event/'),
        ),
    ]
